version: 2.1
orbs:
  docker: circleci/docker@2.6.0
workflows:
  build-push-docker:
    jobs:
      - docker/publish:
          image: leonpatmore/json-server-docker
          tag: $CIRCLE_SHA1,latest
          update-description: true
